### ISSUE TITLE
How to use this tool to parse 3d-front to get 2d layout?

### ISSUE THREAD

**Issue by universewill** [xheon/3d-front-analyzer#1]
How to use this tool to parse 3d-front to get 2d layout? Can you provide some intrudcutions?

I want to get 2d layout of 3d-front, which contains 2d position infomation and 2d bounding box of funitures.

**Comment by xheon** [comment]
In the current state the tool only extracts basic semantic information about rooms (room types) and furniture. 

It does not parse the structural elements (wall, floor, etc) or loads the furniture. 

Feel free to change the current code to parse scenes layouts.
